# syntax=docker/dockerfile:1
# Generated by dockergen
# repo: https://github.com/mp911de/logstash-gelf.git  parent_sha: 7186df83a47b683acc058cba48bafd784fd52255  commit_date: 2013-10-14T08:06:35+02:00
# confidence: jdk=explicit(pom.xml:properties/maven.compiler.source), maven=default(config.py:MAVEN_DEFAULT_BY_COMMIT_YEAR (commit_date=2013-10-14T08:06:35+02:00)), base_image=inferred
# risks: 3 件 (high: unversioned-plugin)
FROM eclipse-temurin:8-jdk-focal
# 取得失敗時のフォールバック候補: eclipse-temurin:8-jdk, openjdk:8-jdk, amazoncorretto:8

# --- OS packages ---
RUN apt-get update && apt-get install -y --no-install-recommends \
      ca-certificates curl unzip git \
    && rm -rf /var/lib/apt/lists/*

# --- Maven 3.2.5 (default: config.py:MAVEN_DEFAULT_BY_COMMIT_YEAR (commit_date=2013-10-14T08:06:35+02:00)) ---
ENV MAVEN_VERSION=3.2.5
ENV MAVEN_HOME=/opt/maven
RUN set -eux; \
    curl -fsSL -o /tmp/maven.tar.gz "https://archive.apache.org/dist/maven/maven-3/3.2.5/binaries/apache-maven-3.2.5-bin.tar.gz"; \
    mkdir -p "$MAVEN_HOME"; \
    tar -xzf /tmp/maven.tar.gz -C "$MAVEN_HOME" --strip-components=1; \
    rm /tmp/maven.tar.gz; \
    ln -sf "$MAVEN_HOME/bin/mvn" /usr/local/bin/mvn; \
    mvn -v

# --- Repository mirror fix (dead/insecure repos) ---
# 元の pom.xml は書き換えず、settings.xml のミラーとして外から与える (§5.3 / §6.2)
COPY <<'DOCKERGEN_SETTINGS_EOF' /root/.m2/settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Generated by dockergen.
  元の pom.xml は書き換えず、ミラー設定として外から注入している (§5.3 / §6.2)。
-->
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                              https://maven.apache.org/xsd/settings-1.0.0.xsd">
  <mirrors>
    <mirror>
      <id>dockergen-jcenter</id>
      <name>dockergen: JCenter/Bintray は 2021 年に終了</name>
      <mirrorOf>jcenter,bintray,jcenter.bintray.com,central-bintray</mirrorOf>
      <url>https://repo.maven.apache.org/maven2</url>
    </mirror>
    <mirror>
      <id>dockergen-http-to-https</id>
      <name>dockergen: HTTP リポジトリは 2020 年に廃止されたため HTTPS の Central へ</name>
      <mirrorOf>external:http:*</mirrorOf>
      <url>https://repo.maven.apache.org/maven2</url>
    </mirror>
  </mirrors>
</settings>
DOCKERGEN_SETTINGS_EOF

ENV MAVEN_OPTS="-Xmx1g"
ENV LANG=C.UTF-8 TZ=UTC

WORKDIR /workspace

# --- Dependency layer (cache-friendly) ---
COPY pom.xml .
RUN set +e; \
    mvn -B dependency:go-offline > /tmp/dockergen-go-offline.log 2>&1; \
    echo $? > /tmp/dockergen-go-offline.exit; \
    tail -n 30 /tmp/dockergen-go-offline.log; \
    echo "dockergen: dependency:go-offline exit=$(cat /tmp/dockergen-go-offline.exit)"; \
    exit 0

# --- Source ---
COPY . .

# --- Build ---
RUN mvn -B -DskipTests package

CMD ["mvn", "-B", "test"]
